import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow.variable}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
